interface TBlog {
    _id:string;
    title: string;
    description: string;
    Tags: string[];
    coverImage: string;
    createdAt?: Date; // Optional because they are generated by Mongoose
    updatedAt?: Date; // Optional because they are generated by Mongoose
  }
  
  export default TBlog;
  